from persistence.datasource.mysql_impl import MySQLConnection
from persistence.datasource.redis_impl import RedisConnection
from persistence.datasource.elasticsearch_impl import ElasticsearchConnection
